# Generated by Django 5.1.1 on 2024-09-30 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RequestLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.GenericIPAddressField()),
                ('user_agent', models.CharField(blank=True, max_length=256, null=True)),
                ('path', models.CharField(blank=True, max_length=256, null=True)),
                ('method', models.CharField(blank=True, max_length=10, null=True)),
                ('headers', models.TextField(blank=True, null=True)),
                ('referrer', models.CharField(blank=True, max_length=256, null=True)),
                ('response_status', models.IntegerField(blank=True, default=200, null=True)),
                ('session_key', models.CharField(blank=True, max_length=40, null=True)),
            ],
            options={
                'verbose_name': 'Request Log',
                'verbose_name_plural': 'Request Logs',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='ViewCount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_views', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Visitor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField()),
                ('device_type', models.CharField(max_length=50)),
                ('visit_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='HourlyViewCount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('hour', models.PositiveIntegerField()),
                ('view_count', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Hourly View Count',
                'verbose_name_plural': 'Hourly View Counts',
                'unique_together': {('date', 'hour')},
            },
        ),
    ]
