# Generated by Django 5.1.1 on 2024-09-28 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('counter_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyViewCount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('view_count', models.PositiveIntegerField(default=0)),
            ],
        ),
    ]
