# Generated by Django 5.1.1 on 2024-10-01 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('counter_app', '0002_requestlog_city_requestlog_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestlog',
            name='autonomous_system_number',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='requestlog',
            name='autonomous_system_organization',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
